version: '3.8'

services:
  app:
    build: .
    image: express-mongo-app
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: